# Generated by Django 3.2.4 on 2021-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_name_u',
            field=models.CharField(default='sdsd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name_u',
            field=models.CharField(default='sdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='people.Achievements'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='additional_education',
            field=models.ManyToManyField(blank=True, null=True, to='people.Education'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='people.Experience'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='people.Skills'),
        ),
    ]
