# Generated by Django 3.2.4 on 2021-10-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_achievements_education_experience_skills_useraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Дополнительное образование', 'verbose_name_plural': 'Дополнительные образования'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работ'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='experience',
            name='photo_work',
            field=models.ImageField(upload_to='static/photo_works'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(upload_to='static/photos'),
        ),
    ]
