# Generated by Django 3.2.4 on 2021-10-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20211017_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='photo_education',
            field=models.ImageField(default='1', upload_to='static/photo_education'),
            preserve_default=False,
        ),
    ]
